---
# tasks file for lighthouse
- block:
  - name: add repo nginx
    ansible.builtin.copy:
      dest: /etc/yum.repos.d/nginx.repo
      mode: '0755'
      content: |
        [nginx]
        name=nginx repo
        baseurl=https://nginx.org/packages/centos/$releasever/$basearch/
        gpgcheck=0
        enabled=1

  - name: install nginx and git
    ansible.builtin.yum:
      name:
        - nginx
        - git
      state: latest
      update_cache: yes
    when: not ansible_check_mode

  - name: Get lighthouse from git
    ansible.builtin.git:
      repo: 'https://github.com/VKCOM/lighthouse.git'
      dest: "{{ lighthouse_home_dir }}"
    when: not ansible_check_mode

  - name: Configure nginx from template
    ansible.builtin.template:
      src: lighthouse.conf.j2
      dest: "{{ nginx_config_dir }}/conf.d/default.conf"
  become: true
  notify: restarted nginx service
- name: Flush handlers
  meta: flush_handlers
